{{- if .Values.global_config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Values.global_config.name }}
data:
  MQTT_HOST: {{ .Release.Name }}-rabbitmq-ha
  MQTT_PORT: 5672
 {{- range $key, $value := .Values.global_config.data }}
  {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- end }}
