apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  https://www.rabbitmq.com/mqtt.html#config
  enabled_plugins: |
    [rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,rabbitmq_web_mqtt,rabbitmq_peer_discovery_k8s,rabbitmq_shovel,rabbitmq_shovel_management].

  rabbitmq.conf: |
    ## RabbitMQ configuration
    ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example

    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = ip
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = false
    cluster_partition_handling = autoheal

    ## The default "guest" user is only permitted to access the server
    ## via a loopback interface (e.g. localhost)
    loopback_users.guest = false

    ## Memory-based Flow Control threshold
    vm_memory_high_watermark.absolute = {{ index .Values "rabbitmq-ha" "rabbitmqMemoryHighWatermark" }}

    listeners.tcp.default = none
    # documentation for this is pretty terrible...
    web_mqtt.port = 5672

    mqtt.default_user     = cool-person
  {{ if index .Values "rabbitmq-ha" "rabbitmqPassword" }}
    rabbitmq-password: {{ index .Values "rabbitmq-ha" "rabbitmqPassword" | b64enc | quote }}
  {{ else }}
    rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
    mqtt.allow_anonymous  = false
    mqtt.vhost            = /mqtt
    mqtt.exchange         = amq.topic
    # 24 hours by default
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch         = 10
    mqtt.listeners.ssl    = none
    ## Default MQTT with TLS port is 8883
    # mqtt.listeners.ssl.default = 8883
    # mqtt.listeners.tcp.default = 1883
    mqtt.tcp_listen_options.backlog = 128
    mqtt.tcp_listen_options.nodelay = true
