apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-vernemq
  labels:
    app: {{ template "name" . }}-vernemq
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.service.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: websock
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 5000
    targetPort: 5000
    name: webhooks
  selector:
    app: {{ template "name" . }}-vernemq
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  type: NodePort
