apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-vernemq
  labels:
    app: {{ template "name" . }}-vernemq
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.service.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 1883
    targetPort: 1883
    name: http
    protocol: TCP
  selector:
    app: {{ template "name" . }}-vernemq
    component: {{ .Values.service.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  type: NodePort
