---

stages:
    - tests
    - build
    - deploy

.docker_build_common: &docker_build_common
    image: michaelboulton/rocker-deploy:latest
    tags:
        - dind
    services:
        - docker:dind

#####################################################

variables:
    GIT_SSL_CAPATH: /etc/ssl/certs/
    GIT_SUBMODULE_STRATEGY: recursive

    GCR_REGISTRY_PREFIX: eu.gcr.io/
    GCLOUD_PROJECT_NAME: overlock-192311
    GCLOUD_CLUSTER_NAME: mqtt-broker
    GCLOUD_COMPUTE_ZONE: europe-west1-b

    GCLOUD_VER: 184.0.0

    # Extra things that need to be set:
    # GCLOUD_CONTAINER_AUTH: Look at helm-deployment-start README on how to get this
    # KUBE_NAMESPACE: set via gitlab kubernetes integration
    # KUBECONFIG: set via gitlab kubernetes integration


Run tests:
    # TODO
    image: michaelboulton/python-package-build:3.5-slim-jessie
    stage: tests
    tags:
        - kwak

    before_script:
        - cd overlock-mqtt-auth/
        - pip install .[vernemq] pylint
    script:
        - pylint overlockmqttauth


Build webhooks container:
    <<: *docker_build_common
    stage: build

    only:
        - tags

    variables:
        IMAGE_NAME: ${GCR_REGISTRY_PREFIX}/${GCLOUD_PROJECT_NAME}/mockson-webhooks:${CI_COMMIT_TAG}

    before_script:
        - apk update && apk --no-cache add python
        - curl -SL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUD_VER}-linux-x86_64.tar.gz | tar xz
        - echo $GCLOUD_CONTAINER_AUTH | base64 -d > /tmp/auth.json
        - export GCLOUDBIN=$(pwd)/google-cloud-sdk/bin/gcloud
        # login
        - $GCLOUDBIN auth activate-service-account --key-file /tmp/auth.json
        # update
        - $GCLOUDBIN --quiet components update
        # get credentials
        - $GCLOUDBIN config set project $GCLOUD_PROJECT_NAME

    script:
        - cd overlock-mqtt-auth
        - >
            docker build .
            -t ${IMAGE_NAME}
            -f Dockerfile.vernemq
        - $GCLOUDBIN docker -- push ${IMAGE_NAME}


Deploy tagged version to integration:
    <<: *docker_build_common
    image: michaelboulton/helmdeploy:v2.7.2

    stage: deploy

    environment:
        name: integration

    variables:
        GIT_SUBMODULE_STRATEGY: none
        TILLER_NAMESPACE: $KUBE_NAMESPACE

    before_script:
        - helm init --upgrade --service-account=tiller-sa
        - sleep 10
        - helm list
    script:
        - >
            helm upgrade
            --namespace $KUBE_NAMESPACE
            $(helm list | grep mockson | awk '{print $1}')
            chart/mockson
    only:
        - tags
