version: '2.0'
services:
        proxy:
                image: traefik
                command: -c /dev/null --web --docker --docker.domain=messaging.localhost --logLevel=DEBUG
                ports:
                        - "80:80"
                        - "8080:8080"
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"
        vernemq:
                image: erlio/docker-vernemq
                volumes:
                        - "./docker-vernemq/vernemq.conf:/etc/vernemq/vernemq.conf"
                env_file:
                        - "./docker-vernemq/vmq.vars"
                ports:
                        - "1883"
                depends_on:
                        - mongo
                        - mongo-setup
                labels:
                        - "traefik.backend=vernemq"
                        - "traefik.frontend.rule=HostRegexp:{subdomain:[0-9a-z]+}.messaging.localhost"
                        - "traefik.enable=true"
                        - "traefik.port=1883"
        mongo:
                image: mongo:latest
                volumes:
                        - mongo_data:/data/db
                ports:
                        - "27017"
                labels:
                        - "traefik.enable=false"
        mongo-setup:
                build: ./seed-mongo
                depends_on:
                        - mongo
                environment:
                        - MONGO_HOST=mongo
                labels:
                        - "traefik.enable=false"
        hooks:
                build: ./app
                depends_on:
                        - vernemq
                labels:
                        - "traefik.enable=false"
                ports:
                        - "5000:5000"
                environment:
                        - MQTT_HOST=vernemq
                        - MQTT_PORT=1883
                        - HOOK_PORT=5000
volumes:
        mongo_data:
