---
version: '2.0'

services:

  vernemq:
    image: erlio/docker-vernemq
    # volumes:
    #   - "./vernemq/files/config/vernemq.conf:/etc/vernemq/vernemq.conf"
    # env_file:
    #   - "./vernemq/files/config/vm.args"
    volumes:
      - "./vernemq/files/config/:/etc/vernemq/"
    ports:
      - "1883:1883"
      - "8080:8080"
    depends_on:
      - mongodb
      - mongo-setup

  mongodb:
    image: mongo:latest
    # volumes:
    #   - mongo_data:/data/db
    ports:
      - "27000:27017"

  mongo-setup:
    build:  # ./seed-mongo
      context: ./seed-mongo
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb

  hooks:
    build:
      context: ./overlock-mqtt-auth
      dockerfile: Dockerfile.vernemq
    depends_on:
      - vernemq
    ports:
      - "5000:5000"
    environment:
      MQTT_HOST: vernemq
      MQTT_PORT: 1883
      HOOK_PORT: 5000

      MONGO_SSL: "false"
      MONGO_APPNAME: webhooks
      MONGO_DATABASE: vmq_acl_auth

volumes:
  mongo_data:
