version: '2.0'
services:
    vernemq:
        build: ./vernemq
        ports:
            - "1883:1883"
        volumes:
            - "./vernemq/files/config:/etc/vernemq"
            - "/var/log/vernemq"
            - "/var/lib/vernemq"
        links:
            - "web:webhooks"
        labels:
            - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.messaging.vernemq"
    web:
        build: ./app
        ports:
            - "5000:5000"
        volumes:
            - "./app:/code"

    redis:
        image: "redis:alpine"
