---
STUPID_NO_TLS: False
ingress:
  host_backend: mqtt.olapi.io
  paths:
    - /mqtt

service:
  name: broker

deployment:
  replicas: 1

  webhooks:
    image: eu.gcr.io/overlock-192311/mockson-webhooks:0.4.1

    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 15m
        memory: 100Mi

  seed:
    # THIS SHOULD ONLY BE ENABLED IF USING 1 REPLICA!!
    enabled: false
    image: eu.gcr.io/overlock-192311/mockson-seed:0.4.1


rabbitmq-ha:

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 15m
      memory: 100Mi
  rabbitmqMemoryHighWatermark: 300MB

  replicaCount: 1


  ## You might see 20-50% better performance at the cost
  ## of a few minutes delay at startup.
  rabbitmqHipeCompile: false

  persistentVolume:
    # disabled by default
    enabled: false

  rbac:
    create: true
    serviceAccountName: rabbitmq


# ConfigMap - each value is set as an environment variable in every container
global_config:
  name: exampleconfig
  create: true
  data:
    GET_HOSTS_FROM: dns

    # used by erlang pod only
    WAIT_FOR_ERLANG: 600

    HOOK_PORT: 5000

    MONGO_HOST: 'mongodb://cluster0-shard-00-00-skv03.mongodb.net,cluster0-shard-00-01-skv03.mongodb.net,cluster0-shard-00-02-skv03.mongodb.net/integration?replicaSet=Cluster0-shard-0&ssl=true&authSource=admin'
    MONGO_DB: integration
    MONGO_PORT: 27017
    MONGO_USERNAME: integration-rw
    MONGO_PASSWORD: z0JZw67N0XJSrJZ1
    MONGO_SSL: true

    OVERLOCK_WORKER_PASSWORD: tae7Ielonguafaf1aS7a


# mongodb:
#   persistence:
#     enabled: false
#
#   resources:
#     limits:
#       cpu: 100m
#       memory: 500Mi
#     requests:
#       cpu: 100m
#       memory: 256Mi
