---
STUPID_NO_TLS: true
ingress:
  host_backend: testbroker.olapi.io
  paths:
    - /mqtt

service:
  name: broker

deployment:
  replicas: 1

  broker:
    image: erlio/docker-vernemq:1.2.0

    resources:
      limits:
        cpu: 100m
        memory: 400Mi
      requests:
        cpu: 25m
        memory: 400Mi

    extra_config:
      # Shared values for clusters
      # This is set to the name of the release if not set here
      ## IMPORTANT!!! set to a random value, not 'vmq' or something like that
      distributed_cookie:

  webhooks:
    image: eu.gcr.io/overlock-192311/mockson-webhooks:0.3.19

    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 25m
        memory: 100Mi

  seed:
    # THIS SHOULD ONLY BE ENABLED IF USING 1 REPLICA!!
    enabled: false
    image: eu.gcr.io/overlock-192311/mockson-seed:0.3.19


# ConfigMap - each value is set as an environment variable in every container
global_config:
  name: exampleconfig
  create: true
  data:
    GET_HOSTS_FROM: dns

    # used by erlang pod only
    WAIT_FOR_ERLANG: 600

    MQTT_HOST: vernemq
    MQTT_PORT: 8080
    HOOK_PORT: 5000

    MONGO_HOST: 'mongodb://cluster0-shard-00-00-skv03.mongodb.net,cluster0-shard-00-01-skv03.mongodb.net,cluster0-shard-00-02-skv03.mongodb.net/integration?replicaSet=Cluster0-shard-0&ssl=true&authSource=admin'
    MONGO_DB: integration
    MONGO_PORT: 27017
    MONGO_USERNAME: integration-rw
    MONGO_PASSWORD: z0JZw67N0XJSrJZ1
    MONGO_SSL: true

    OVERLOCK_WORKER_PASSWORD: tae7Ielonguafaf1aS7a


# mongodb:
#   persistence:
#     enabled: false
#
#   resources:
#     limits:
#       cpu: 100m
#       memory: 500Mi
#     requests:
#       cpu: 100m
#       memory: 256Mi
